name: Packages build

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
      fail-fast: false
    steps:
    - name: run on linux
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install libarchive-tools
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - uses: actions/setup-node@v3
      with:
        node-version: '18.17.1'
    - run: npm install npm@9 -g
    - run: npm install
    - run: node_modules/.bin/electron-builder build
      env:
        GH_TOKEN: ${{ secrets.github_token }}
